(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var v;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var w=da(this);function z(a,b){if(b)a:{var c=w;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}
z("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.h=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.h};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
z("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=w[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(aa(this))}})}return a});function ea(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function A(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function fa(a){if(!(a instanceof Array)){a=A(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ha="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)Object.prototype.hasOwnProperty.call(d,e)&&(a[e]=d[e])}return a};z("Object.assign",function(a){return a||ha});
var ia="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ja;if("function"==typeof Object.setPrototypeOf)ja=Object.setPrototypeOf;else{var ka;a:{var la={a:!0},ma={};try{ma.__proto__=la;ka=ma.a;break a}catch(a){}ka=!1}ja=ka?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var na=ja;
function B(a,b){a.prototype=ia(b.prototype);a.prototype.constructor=a;if(na)na(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.za=b.prototype}function oa(){this.m=!1;this.j=null;this.i=void 0;this.h=1;this.v=this.s=0;this.l=null}function pa(a){if(a.m)throw new TypeError("Generator is already running");a.m=!0}oa.prototype.u=function(a){this.i=a};
function qa(a,b){a.l={ma:b,na:!0};a.h=a.s||a.v}oa.prototype.return=function(a){this.l={return:a};this.h=this.v};function C(a,b,c){a.h=c;return{value:b}}function ra(a){this.h=new oa;this.i=a}function sa(a,b){pa(a.h);var c=a.h.j;if(c)return ta(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.h.return);a.h.return(b);return ua(a)}
function ta(a,b,c,d){try{var e=b.call(a.h.j,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.h.m=!1,e;var f=e.value}catch(g){return a.h.j=null,qa(a.h,g),ua(a)}a.h.j=null;d.call(a.h,f);return ua(a)}function ua(a){for(;a.h.h;)try{var b=a.i(a.h);if(b)return a.h.m=!1,{value:b.value,done:!1}}catch(c){a.h.i=void 0,qa(a.h,c)}a.h.m=!1;if(a.h.l){b=a.h.l;a.h.l=null;if(b.na)throw b.ma;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function va(a){this.next=function(b){pa(a.h);a.h.j?b=ta(a,a.h.j.next,b,a.h.u):(a.h.u(b),b=ua(a));return b};this.throw=function(b){pa(a.h);a.h.j?b=ta(a,a.h.j["throw"],b,a.h.u):(qa(a.h,b),b=ua(a));return b};this.return=function(b){return sa(a,b)};this[Symbol.iterator]=function(){return this}}function wa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function D(a){return wa(new va(new ra(a)))}
z("Promise",function(a){function b(g){this.i=0;this.j=void 0;this.h=[];this.u=!1;var h=this.l();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.h=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.i=function(g){if(null==this.h){this.h=[];var h=this;this.j(function(){h.m()})}this.h.push(g)};var e=w.setTimeout;c.prototype.j=function(g){e(g,0)};c.prototype.m=function(){for(;this.h&&this.h.length;){var g=this.h;this.h=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(l){this.l(l)}}}this.h=null};c.prototype.l=function(g){this.j(function(){throw g;})};b.prototype.l=function(){function g(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:g(this.I),reject:g(this.m)}};b.prototype.I=function(g){if(g===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.L(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.F(g):this.s(g)}};
b.prototype.F=function(g){var h=void 0;try{h=g.then}catch(k){this.m(k);return}"function"==typeof h?this.M(h,g):this.s(g)};b.prototype.m=function(g){this.v(2,g)};b.prototype.s=function(g){this.v(1,g)};b.prototype.v=function(g,h){if(0!=this.i)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.i);this.i=g;this.j=h;2===this.i&&this.K();this.H()};b.prototype.K=function(){var g=this;e(function(){if(g.D()){var h=w.console;"undefined"!==typeof h&&h.error(g.j)}},1)};b.prototype.D=
function(){if(this.u)return!1;var g=w.CustomEvent,h=w.Event,k=w.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof h?g=new h("unhandledrejection",{cancelable:!0}):(g=w.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.j;return k(g)};b.prototype.H=function(){if(null!=this.h){for(var g=0;g<this.h.length;++g)f.i(this.h[g]);this.h=null}};var f=new c;b.prototype.L=
function(g){var h=this.l();g.T(h.resolve,h.reject)};b.prototype.M=function(g,h){var k=this.l();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,h){function k(p,n){return"function"==typeof p?function(q){try{l(p(q))}catch(t){m(t)}}:n}var l,m,r=new b(function(p,n){l=p;m=n});this.T(k(g,l),k(h,m));return r};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.T=function(g,h){function k(){switch(l.i){case 1:g(l.j);break;case 2:h(l.j);break;default:throw Error("Unexpected state: "+
l.i);}}var l=this;null==this.h?f.i(k):this.h.push(k);this.u=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var l=A(g),m=l.next();!m.done;m=l.next())d(m.value).T(h,k)})};b.all=function(g){var h=A(g),k=h.next();return k.done?d([]):new b(function(l,m){function r(q){return function(t){p[q]=t;n--;0==n&&l(p)}}var p=[],n=0;do p.push(void 0),n++,d(k.value).T(r(p.length-1),m),k=h.next();while(!k.done)})};return b});
function xa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}z("Array.prototype.keys",function(a){return a?a:function(){return xa(this,function(b){return b})}});
z("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function E(a){return a?a:Array.prototype.fill}z("Int8Array.prototype.fill",E);z("Uint8Array.prototype.fill",E);z("Uint8ClampedArray.prototype.fill",E);z("Int16Array.prototype.fill",E);z("Uint16Array.prototype.fill",E);z("Int32Array.prototype.fill",E);
z("Uint32Array.prototype.fill",E);z("Float32Array.prototype.fill",E);z("Float64Array.prototype.fill",E);z("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});z("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
z("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(b,c||0)}});var ya=this||self;
function za(a,b){a=a.split(".");var c=ya;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};function Aa(a){var b;a:{if(b=ya.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};var Ba=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};var Ca={},Da=null;function Ea(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):-1!="=.".indexOf(a[b-1])&&(c=-1!="=.".indexOf(a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;Fa(a,function(f){d[e++]=f});return e!==c?d.subarray(0,e):d}
function Fa(a,b){function c(k){for(;d<a.length;){var l=a.charAt(d++),m=Da[l];if(null!=m)return m;if(!/^[\s\xa0]*$/.test(l))throw Error("Unknown base64 encoding at char: "+l);}return k}Ga();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(64===h&&-1===e)break;b(e<<2|f>>4);64!=g&&(b(f<<4&240|g>>2),64!=h&&b(g<<6&192|h))}}
function Ga(){if(!Da){Da={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));Ca[c]=d;for(var e=0;e<d.length;e++){var f=d[e];void 0===Da[f]&&(Da[f]=e)}}}};var Ha="undefined"!==typeof Uint8Array,Ia=!(Aa("Trident")||Aa("MSIE"))&&"function"===typeof ya.btoa;
function Ja(a){if(!Ia){var b;void 0===b&&(b=0);Ga();b=Ca[b];for(var c=Array(Math.floor(a.length/3)),d=b[64]||"",e=0,f=0;e<a.length-2;e+=3){var g=a[e],h=a[e+1],k=a[e+2],l=b[g>>2];g=b[(g&3)<<4|h>>4];h=b[(h&15)<<2|k>>6];k=b[k&63];c[f++]=l+g+h+k}l=0;k=d;switch(a.length-e){case 2:l=a[e+1],k=b[(l&15)<<2]||d;case 1:a=a[e],c[f]=b[a>>2]+b[(a&3)<<4|l>>4]+k+d}return c.join("")}for(b="";10240<a.length;)b+=String.fromCharCode.apply(null,a.subarray(0,10240)),a=a.subarray(10240);b+=String.fromCharCode.apply(null,
a);return btoa(b)}var Ka=RegExp("[-_.]","g");function La(a){switch(a){case "-":return"+";case "_":return"/";case ".":return"=";default:return""}}function Ma(a){if(!Ia)return Ea(a);Ka.test(a)&&(a=a.replace(Ka,La));a=atob(a);for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b}var Na;function Oa(){return Na||(Na=new Uint8Array(0))}var Pa={};var Ra="function"===typeof Uint8Array.prototype.slice,H=0,I=0;function Sa(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);b&&(c=A(Ta(c,a)),b=c.next().value,a=c.next().value,c=b);H=c>>>0;I=a>>>0}
function Ua(a){a=+a;if(0===a)0<1/a?H=I=0:(I=0,H=2147483648);else if(isNaN(a))I=0,H=2147483647;else{var b=0>a?-2147483648:0;a=b?-a:a;if(3.4028234663852886E38<a)I=0,H=(b|2139095040)>>>0;else if(1.1754943508222875E-38>a)a=Math.round(a/Math.pow(2,-149)),I=0,H=(b|a)>>>0;else{var c=Math.floor(Math.log(a)/Math.LN2);a*=Math.pow(2,-c);a=Math.round(8388608*a);16777216<=a&&++c;I=0;H=(b|c+127<<23|a&8388607)>>>0}}}var Va="function"===typeof BigInt;function Ta(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function Wa(a,b){this.i=a>>>0;this.h=b>>>0}
function Xa(a){if(!a)return Ya||(Ya=new Wa(0,0));if(!/^-?\d+$/.test(a))return null;if(16>a.length)Sa(Number(a));else if(Va)a=BigInt(a),H=Number(a&BigInt(4294967295))>>>0,I=Number(a>>BigInt(32)&BigInt(4294967295));else{var b=+("-"===a[0]);I=H=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),I*=1E6,H=1E6*H+d,4294967296<=H&&(I+=H/4294967296|0,H%=4294967296);b&&(b=A(Ta(H,I)),a=b.next().value,b=b.next().value,H=a,I=b)}return new Wa(H,I)}var Ya;function Za(a,b){return Error("Invalid wire type: "+a+" (at position "+b+")")}function $a(){return Error("Failed to read varint, encoding is invalid.")}function ab(a,b){return Error("Tried to read past the end of the data "+b+" > "+a)};function bb(){throw Error("Invalid UTF8");}function cb(a,b){b=String.fromCharCode.apply(null,b);return null==a?b:a+b}var db=void 0,eb,fb="undefined"!==typeof TextDecoder,gb,hb="undefined"!==typeof TextEncoder;var ib;function jb(a){if(a!==Pa)throw Error("illegal external caller");}function kb(a,b){jb(b);this.V=a;if(null!=a&&0===a.length)throw Error("ByteString should be constructed with non-empty values");}function lb(){return ib||(ib=new kb(null,Pa))}function mb(a){jb(Pa);var b=a.V;b=null==b||Ha&&null!=b&&b instanceof Uint8Array?b:"string"===typeof b?Ma(b):null;return null==b?b:a.V=b};function nb(a){if("string"===typeof a)return{buffer:Ma(a),C:!1};if(Array.isArray(a))return{buffer:new Uint8Array(a),C:!1};if(a.constructor===Uint8Array)return{buffer:a,C:!1};if(a.constructor===ArrayBuffer)return{buffer:new Uint8Array(a),C:!1};if(a.constructor===kb)return{buffer:mb(a)||Oa(),C:!0};if(a instanceof Uint8Array)return{buffer:new Uint8Array(a.buffer,a.byteOffset,a.byteLength),C:!1};throw Error("Type not convertible to a Uint8Array, expected a Uint8Array, an ArrayBuffer, a base64 encoded string, a ByteString or an Array of numbers");
};function ob(a,b){this.i=null;this.s=!1;this.h=this.j=this.l=0;pb(this,a,b)}function pb(a,b,c){c=void 0===c?{}:c;a.S=void 0===c.S?!1:c.S;b&&(b=nb(b),a.i=b.buffer,a.s=b.C,a.l=0,a.j=a.i.length,a.h=a.l)}ob.prototype.reset=function(){this.h=this.l};function qb(a,b){a.h=b;if(b>a.j)throw ab(a.j,b);}
function rb(a){var b=a.i,c=a.h,d=b[c++],e=d&127;if(d&128&&(d=b[c++],e|=(d&127)<<7,d&128&&(d=b[c++],e|=(d&127)<<14,d&128&&(d=b[c++],e|=(d&127)<<21,d&128&&(d=b[c++],e|=d<<28,d&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128)))))throw $a();qb(a,c);return e}function sb(a){var b=a.i,c=a.h,d=b[c],e=b[c+1],f=b[c+2];b=b[c+3];qb(a,a.h+4);return(d<<0|e<<8|f<<16|b<<24)>>>0}
ob.prototype.m=function(){var a=sb(this),b=2*(a>>31)+1,c=a>>>23&255;a&=8388607;return 255==c?a?NaN:Infinity*b:0==c?b*Math.pow(2,-149)*a:b*Math.pow(2,c-150)*(a+Math.pow(2,23))};function tb(a){for(var b=0,c=a.h,d=c+10,e=a.i;c<d;){var f=e[c++];b|=f;if(0===(f&128))return qb(a,c),!!(b&127)}throw $a();}function ub(a,b){if(0>b)throw Error("Tried to read a negative byte length: "+b);var c=a.h,d=c+b;if(d>a.j)throw ab(b,a.j-c);a.h=d;return c}var vb=[];function wb(){this.h=[]}wb.prototype.length=function(){return this.h.length};wb.prototype.end=function(){var a=this.h;this.h=[];return a};function xb(a,b,c){for(;0<c||127<b;)a.h.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.h.push(b)}function yb(a,b){for(;127<b;)a.h.push(b&127|128),b>>>=7;a.h.push(b)}function zb(a,b){if(0<=b)yb(a,b);else{for(var c=0;9>c;c++)a.h.push(b&127|128),b>>=7;a.h.push(1)}}function Ab(a,b){a.h.push(b>>>0&255);a.h.push(b>>>8&255);a.h.push(b>>>16&255);a.h.push(b>>>24&255)};function Bb(a,b){if(vb.length){var c=vb.pop();pb(c,a,b);a=c}else a=new ob(a,b);this.h=a;this.j=this.h.h;this.i=this.l=-1;this.setOptions(b)}Bb.prototype.setOptions=function(a){a=void 0===a?{}:a;this.ca=void 0===a.ca?!1:a.ca};Bb.prototype.reset=function(){this.h.reset();this.j=this.h.h;this.i=this.l=-1};
function Cb(a){var b=a.h;if(b.h==b.j)return!1;a.j=a.h.h;var c=rb(a.h)>>>0;b=c>>>3;c&=7;if(!(0<=c&&5>=c))throw Za(c,a.j);if(1>b)throw Error("Invalid field number: "+b+" (at position "+a.j+")");a.l=b;a.i=c;return!0}
function Db(a){switch(a.i){case 0:0!=a.i?Db(a):tb(a.h);break;case 1:a=a.h;qb(a,a.h+8);break;case 2:if(2!=a.i)Db(a);else{var b=rb(a.h)>>>0;a=a.h;qb(a,a.h+b)}break;case 5:a=a.h;qb(a,a.h+4);break;case 3:b=a.l;do{if(!Cb(a))throw Error("Unmatched start-group tag: stream EOF");if(4==a.i){if(a.l!=b)throw Error("Unmatched end-group tag");break}Db(a)}while(1);break;default:throw Za(a.i,a.j);}}
function Eb(a,b,c){var d=a.h.j,e=rb(a.h)>>>0,f=a.h.h+e,g=f-d;0>=g&&(a.h.j=f,c(b,a,void 0,void 0,void 0),g=f-a.h.h);if(g)throw Error("Message parsing ended unexpectedly. Expected to read "+(e+" bytes, instead read "+(e-g)+" bytes, either the data ended unexpectedly or the message misreported its own length"));a.h.h=f;a.h.j=d}var Fb=[];function Gb(){this.j=[];this.i=0;this.h=new wb}function Hb(a,b){0!==b.length&&(a.j.push(b),a.i+=b.length)}function Ib(a,b){J(a,b,2);b=a.h.end();Hb(a,b);b.push(a.i);return b}function Jb(a,b){var c=b.pop();for(c=a.i+a.h.length()-c;127<c;)b.push(c&127|128),c>>>=7,a.i++;b.push(c);a.i++}function Kb(a,b){if(b=b.R){Hb(a,a.h.end());for(var c=0;c<b.length;c++)Hb(a,mb(b[c])||Oa())}}function J(a,b,c){yb(a.h,8*b+c)};var K="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0;function M(a,b){if(K)return a[K]|=b;if(void 0!==a.B)return a.B|=b;Object.defineProperties(a,{B:{value:b,configurable:!0,writable:!0,enumerable:!1}});return b}function Lb(a,b){var c=N(a);(c&b)!==b&&(Object.isFrozen(a)&&(a=Array.prototype.slice.call(a)),O(a,c|b));return a}function Mb(a,b){K?a[K]&&(a[K]&=~b):void 0!==a.B&&(a.B&=~b)}function N(a){var b;K?b=a[K]:b=a.B;return null==b?0:b}
function O(a,b){K?a[K]=b:void 0!==a.B?a.B=b:Object.defineProperties(a,{B:{value:b,configurable:!0,writable:!0,enumerable:!1}})}function Nb(a){M(a,1);return a}function Q(a){return!!(N(a)&2)}function Ob(a,b){O(b,(a|0)&-51)}function Pb(a,b){O(b,(a|18)&-41)};var Qb={};function Rb(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var Sb,Tb=[];O(Tb,23);Sb=Object.freeze(Tb);function Ub(a){if(Q(a.o))throw Error("Cannot mutate an immutable Message");}function Vb(a){var b=a.length;(b=b?a[b-1]:void 0)&&Rb(b)?b.g=1:(b={},a.push((b.g=1,b)))};function Wb(a){if(null!=a&&"number"!==typeof a)throw Error("Value of float/double field must be a number|null|undefined, found "+typeof a+": "+a);return a}function Xb(a){if(null==a)return a;if("number"===typeof a||"NaN"===a||"Infinity"===a||"-Infinity"===a)return Number(a)}function Yb(a,b,c){var d=!1;if(null!=a&&"object"===typeof a&&!(d=Array.isArray(a))&&a.fa===Qb)return a;if(d)return new b(a);if(c)return new b};function Zb(a){var b=a.i+a.G;return a.A||(a.A=a.o[b]={})}function R(a,b,c){return-1===b?null:b>=a.i?a.A?a.A[b]:void 0:c&&a.A&&(c=a.A[b],null!=c)?c:a.o[b+a.G]}function S(a,b,c,d){Ub(a);T(a,b,c,d)}function T(a,b,c,d){a.j&&(a.j=void 0);b>=a.i||d?Zb(a)[b]=c:(a.o[b+a.G]=c,(a=a.A)&&b in a&&delete a[b])}
function $b(a,b,c,d,e){var f=R(a,b,d);Array.isArray(f)||(f=Sb);var g=N(f);g&1||Nb(f);if(e)g&2||M(f,2),c&1||Object.freeze(f);else{e=!(c&2);var h=g&2;c&1||!h?e&&g&16&&!h&&Mb(f,16):(f=Nb(Array.prototype.slice.call(f)),T(a,b,f,d))}return f}function ac(a,b){var c=R(a,b),d=Xb(c);null!=d&&d!==c&&T(a,b,d);return d}
function bc(a,b){var c=Q(a.o),d=$b(a,b,1,void 0,c),e=N(d);if(!(e&4)){Object.isFrozen(d)&&(d=Nb(d.slice()),T(a,b,d));for(var f=0,g=0;f<d.length;f++){var h=Xb(d[f]);null!=h&&(d[g++]=h)}g<f&&(d.length=g);M(d,5);c&&(M(d,2),Object.freeze(d))}!c&&(e&2||Object.isFrozen(d))&&(d=Array.prototype.slice.call(d),M(d,5),c=d,c=null==c?Sb:Lb(c,1),S(a,b,c));return d}function cc(a,b,c,d){Ub(a);c!==d?T(a,b,c):T(a,b,void 0,!1)}
function dc(a,b,c){var d=void 0===d?!1:d;var e=R(a,c,d);b=Yb(e,b);b!==e&&null!=b&&(T(a,c,b,d),M(b.o,N(a.o)&18));e=b;if(null==e)return e;Q(a.o)||(b=ec(e),b!==e&&(e=b,T(a,c,e,d)));return e}
function fc(a,b,c,d,e){a.h||(a.h={});var f=a.h[c],g=$b(a,c,3,void 0,e);if(!f){var h=g;f=[];var k=!!(N(a.o)&16);g=Q(h);var l=h;!e&&g&&(h=Array.prototype.slice.call(h));for(var m=g,r=0;r<h.length;r++){var p=h[r];var n=b,q=!1;q=void 0===q?!1:q;p=Array.isArray(p)?new n(p):q?new n:void 0;if(void 0!==p){n=p.o;var t=q=N(n);g&&(t|=2);k&&(t|=16);t!=q&&O(n,t);n=t;m=m||!!(2&n);f.push(p)}}a.h[c]=f;k=N(h);b=k|33;b=m?b&-9:b|8;k!=b&&(m=h,Object.isFrozen(m)&&(m=Array.prototype.slice.call(m)),O(m,b),h=m);l!==h&&T(a,
c,h);(e||d&&g)&&M(f,2);d&&Object.freeze(f);return f}e||(e=Object.isFrozen(f),d&&!e?Object.freeze(f):!d&&e&&(f=Array.prototype.slice.call(f),a.h[c]=f));return f}function gc(a,b,c){var d=Q(a.o);b=fc(a,b,c,d,d);a=$b(a,c,3,void 0,d);if(!(d||N(a)&8)){for(d=0;d<b.length;d++){c=b[d];var e=ec(c);c!==e&&(b[d]=e,a[d]=e.o)}M(a,8)}return b}function U(a,b,c){S(a,b,Wb(c))}
function hc(a,b,c,d,e){Ub(a);var f=fc(a,c,b,!1,!1);c=null!=d?d:new c;a=$b(a,b,2,void 0,!1);void 0!=e?(f.splice(e,0,c),a.splice(e,0,c.o)):(f.push(c),a.push(c.o));c.C()&&Mb(a,8);return c}function ic(a){a=R(a,1);return null==a?0:a}function jc(a,b){return null==a?b:a}function V(a,b,c){c=void 0===c?0:c;return jc(ac(a,b),c)};var kc;function lc(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a)if(Array.isArray(a)){if(0!==(N(a)&128))return a=Array.prototype.slice.call(a),Vb(a),a}else{if(Ha&&null!=a&&a instanceof Uint8Array)return Ja(a);if(a instanceof kb){var b=a.V;return null==b?"":"string"===typeof b?b:a.V=Ja(b)}}}return a};function mc(a,b,c,d){if(null!=a){if(Array.isArray(a))a=nc(a,b,c,void 0!==d);else if(Rb(a)){var e={},f;for(f in a)e[f]=mc(a[f],b,c,d);a=e}else a=b(a,d);return a}}function nc(a,b,c,d){var e=N(a);d=d?!!(e&16):void 0;a=Array.prototype.slice.call(a);for(var f=0;f<a.length;f++)a[f]=mc(a[f],b,c,d);c(e,a);return a}function oc(a){return a.fa===Qb?a.toJSON():lc(a)}function pc(a,b){a&128&&Vb(b)};function qc(a,b,c){c=void 0===c?Pb:c;if(null!=a){if(Ha&&a instanceof Uint8Array)return a.length?new kb(new Uint8Array(a),Pa):lb();if(Array.isArray(a)){var d=N(a);if(d&2)return a;if(b&&!(d&32)&&(d&16||0===d))return O(a,d|2),a;a=nc(a,qc,d&4?Pb:c,!0);b=N(a);b&4&&b&2&&Object.freeze(a);return a}return a.fa===Qb?rc(a):a}}
function sc(a,b,c,d,e,f,g){if(a=a.h&&a.h[c]){d=N(a);d&2?d=a:(f=Ba(a,rc),Pb(d,f),Object.freeze(f),d=f);Ub(b);f=null==d?Sb:Nb([]);if(null!=d){g=!!d.length;for(a=0;a<d.length;a++){var h=d[a];g=g&&!Q(h.o);f[a]=h.o}f=Lb(f,(g?8:0)|1);b.h||(b.h={});b.h[c]=d}else b.h&&(b.h[c]=void 0);T(b,c,f,e)}else S(b,c,qc(d,f,g),e)}function rc(a){if(Q(a.o))return a;a=tc(a,!0);M(a.o,2);return a}
function tc(a,b){var c=a.o,d=[];M(d,16);var e=a.constructor.h;e&&d.push(e);e=a.A;if(e){d.length=c.length;d.fill(void 0,d.length,c.length);var f={};d[d.length-1]=f}0!==(N(c)&128)&&Vb(d);b=b||a.C()?Pb:Ob;f=a.constructor;kc=d;d=new f(d);kc=void 0;a.R&&(d.R=a.R.slice());f=!!(N(c)&16);for(var g=e?c.length-1:c.length,h=0;h<g;h++)sc(a,d,h-a.G,c[h],!1,f,b);if(e)for(var k in e)sc(a,d,+k,e[k],!0,f,b);return d}function ec(a){if(!Q(a.o))return a;var b=tc(a,!1);b.j=a;return b};function W(a,b,c){null==a&&(a=kc);kc=void 0;var d=this.constructor.i||0,e=0<d,f=this.constructor.h,g=!1;if(null==a){a=f?[f]:[];var h=48;var k=!0;e&&(d=0,h|=128);O(a,h)}else{if(!Array.isArray(a))throw Error();if(f&&f!==a[0])throw Error();var l=h=M(a,0);if(k=0!==(16&l))(g=0!==(32&l))||(l|=32);if(e)if(128&l)d=0;else{if(0<a.length){var m=a[a.length-1];if(Rb(m)&&"g"in m){d=0;l|=128;delete m.g;var r=!0,p;for(p in m){r=!1;break}r&&a.pop()}}}else if(128&l)throw Error();h!==l&&O(a,l)}this.G=(f?0:-1)-d;this.h=
void 0;this.o=a;a:{f=this.o.length;d=f-1;if(f&&(f=this.o[d],Rb(f))){this.A=f;this.i=d-this.G;break a}void 0!==b&&-1<b?(this.i=Math.max(b,d+1-this.G),this.A=void 0):this.i=Number.MAX_VALUE}if(!e&&this.A&&"g"in this.A)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');if(c){b=k&&!g&&!0;e=this.i;var n;for(k=0;k<c.length;k++)g=c[k],g<e?(g+=this.G,(d=a[g])?uc(d,b):a[g]=Sb):(n||(n=Zb(this)),(d=n[g])?uc(d,b):n[g]=Sb)}}
W.prototype.toJSON=function(){return nc(this.o,oc,pc)};W.prototype.C=function(){return Q(this.o)};function uc(a,b){if(Array.isArray(a)){var c=N(a),d=1;!b||c&2||(d|=16);(c&d)!==d&&O(a,c|d)}}W.prototype.fa=Qb;W.prototype.toString=function(){return this.o.toString()};function vc(a,b,c){if(c){var d={},e;for(e in c){var f=c[e],g=f.ra;g||(d.J=f.xa||f.oa.W,f.ja?(d.aa=wc(f.ja),g=function(h){return function(k,l,m){return h.J(k,l,m,h.aa)}}(d)):f.ka?(d.Z=xc(f.da.P,f.ka),g=function(h){return function(k,l,m){return h.J(k,l,m,h.Z)}}(d)):g=d.J,f.ra=g);g(b,a,f.da);d={J:d.J,aa:d.aa,Z:d.Z}}}Kb(b,a)}var yc=Symbol();function zc(a,b,c){return a[yc]||(a[yc]=function(d,e){return b(d,e,c)})}
function Ac(a){var b=a[yc];if(!b){var c=Bc(a);b=function(d,e){return Cc(d,e,c)};a[yc]=b}return b}function Dc(a){var b=a.ja;if(b)return Ac(b);if(b=a.wa)return zc(a.da.P,b,a.ka)}function Ec(a){var b=Dc(a),c=a.da,d=a.oa.U;return b?function(e,f){return d(e,f,c,b)}:function(e,f){return d(e,f,c)}}function Fc(a,b){var c=a[b];"function"==typeof c&&0===c.length&&(c=c(),a[b]=c);return Array.isArray(c)&&(Gc in c||Hc in c||0<c.length&&"function"==typeof c[0])?c:void 0}
function Ic(a,b,c,d,e,f){b.P=a[0];var g=1;if(a.length>g&&"number"!==typeof a[g]){var h=a[g++];c(b,h)}for(;g<a.length;){c=a[g++];for(var k=g+1;k<a.length&&"number"!==typeof a[k];)k++;h=a[g++];k-=g;switch(k){case 0:d(b,c,h);break;case 1:(k=Fc(a,g))?(g++,e(b,c,h,k)):d(b,c,h,a[g++]);break;case 2:k=g++;k=Fc(a,k);e(b,c,h,k,a[g++]);break;case 3:f(b,c,h,a[g++],a[g++],a[g++]);break;case 4:f(b,c,h,a[g++],a[g++],a[g++],a[g++]);break;default:throw Error("unexpected number of binary field arguments: "+k);}}return b}
var Jc=Symbol();function wc(a){var b=a[Jc];if(!b){var c=Kc(a);b=function(d,e){return Lc(d,e,c)};a[Jc]=b}return b}function xc(a,b){var c=a[Jc];c||(c=function(d,e){return vc(d,e,b)},a[Jc]=c);return c}var Hc=Symbol();function Mc(a,b){a.push(b)}function Nc(a,b,c){a.push(b,c.W)}function Oc(a,b,c,d){var e=wc(d),f=Kc(d).P,g=c.W;a.push(b,function(h,k,l){return g(h,k,l,f,e)})}function Pc(a,b,c,d,e,f){var g=xc(d,f),h=c.W;a.push(b,function(k,l,m){return h(k,l,m,d,g)})}
function Kc(a){var b=a[Hc];if(b)return b;b=Ic(a,a[Hc]=[],Mc,Nc,Oc,Pc);Gc in a&&Hc in a&&(a.length=0);return b}var Gc=Symbol();function Qc(a,b){a[0]=b}function Rc(a,b,c,d){var e=c.U;a[b]=d?function(f,g,h){return e(f,g,h,d)}:e}function Sc(a,b,c,d,e){var f=c.U,g=Ac(d),h=Bc(d).P;a[b]=function(k,l,m){return f(k,l,m,h,g,e)}}function Tc(a,b,c,d,e,f,g){var h=c.U,k=zc(d,e,f);a[b]=function(l,m,r){return h(l,m,r,d,k,g)}}
function Bc(a){var b=a[Gc];if(b)return b;b=Ic(a,a[Gc]={},Qc,Rc,Sc,Tc);Gc in a&&Hc in a&&(a.length=0);return b}
function Cc(a,b,c){for(;Cb(b)&&4!=b.i;){var d=b.l,e=c[d];if(!e){var f=c[0];f&&(f=f[d])&&(e=c[d]=Ec(f))}if(!e||!e(b,a,d)){e=b;d=a;f=e.j;Db(e);var g=e;if(!g.ca){e=g.h.h-f;g.h.h=f;g=g.h;if(0==e)e=lb();else{f=ub(g,e);if(g.S&&g.s)e=g.i.subarray(f,f+e);else{g=g.i;var h=f;e=f+e;e=h===e?Oa():Ra?g.slice(h,e):new Uint8Array(g.subarray(h,e))}e=0==e.length?lb():new kb(e,Pa)}(f=d.R)?f.push(e):d.R=[e]}}}return a}
function Lc(a,b,c){for(var d=c.length,e=1==d%2,f=e?1:0;f<d;f+=2)(0,c[f+1])(b,a,c[f]);vc(a,b,e?c[0]:void 0)}function X(a,b){return{U:a,W:b}}function Uc(a,b,c){b=ac(b,c);null!=b&&(J(a,c,5),a=a.h,Ua(b),Ab(a,H))}function Vc(a,b,c){b=R(b,c);null!=b&&null!=b&&(J(a,c,0),zb(a.h,b))}
var Wc=X(function(a,b,c){if(1!==a.i)return!1;var d=a.h;a=sb(d);var e=sb(d);d=2*(e>>31)+1;var f=e>>>20&2047;a=4294967296*(e&1048575)+a;cc(b,c,Wb(2047==f?a?NaN:Infinity*d:0==f?d*Math.pow(2,-1074)*a:d*Math.pow(2,f-1075)*(a+4503599627370496)),0);return!0},function(a,b,c){b=ac(b,c);if(null!=b){J(a,c,1);a=a.h;var d=+b;if(0===d)I=0<1/d?0:2147483648,H=0;else if(isNaN(d))I=2147483647,H=4294967295;else if(d=(c=0>d?-2147483648:0)?-d:d,1.7976931348623157E308<d)I=(c|2146435072)>>>0,H=0;else if(2.2250738585072014E-308>
d)b=d/Math.pow(2,-1074),I=(c|b/4294967296)>>>0,H=b>>>0;else{var e=d;b=0;if(2<=e)for(;2<=e&&1023>b;)b++,e/=2;else for(;1>e&&-1022<b;)e*=2,b--;d*=Math.pow(2,-b);I=(c|b+1023<<20|1048576*d&1048575)>>>0;H=4503599627370496*d>>>0}Ab(a,H);Ab(a,I)}}),Y=X(function(a,b,c){if(5!==a.i)return!1;S(b,c,a.h.m());return!0},Uc),Z=X(function(a,b,c){if(5!==a.i&&2!==a.i)return!1;b=$b(b,c,0,!1,Q(b.o));if(2==a.i){c=ob.prototype.m;var d=rb(a.h)>>>0;for(d=a.h.h+d;a.h.h<d;)b.push(c.call(a.h))}else b.push(a.h.m());return!0},
function(a,b,c){b=bc(b,c);if(null!=b&&b.length)for(J(a,c,2),yb(a.h,4*b.length),c=0;c<b.length;c++){var d=a.h;Ua(b[c]);Ab(d,H)}}),Xc=X(function(a,b,c){if(5!==a.i)return!1;a=a.h.m();cc(b,c,Wb(a),0);return!0},Uc),Yc=X(function(a,b,c){if(0!==a.i)return!1;var d=a.h,e=0,f=a=0,g=d.i,h=d.h;do{var k=g[h++];e|=(k&127)<<f;f+=7}while(32>f&&k&128);32<f&&(a|=(k&127)>>4);for(f=3;32>f&&k&128;f+=7)k=g[h++],a|=(k&127)<<f;qb(d,h);if(128>k){d=e>>>0;k=a>>>0;if(a=k&2147483648)d=~d+1>>>0,k=~k>>>0,0==d&&(k=k+1>>>0);d=4294967296*
k+(d>>>0)}else throw $a();S(b,c,a?-d:d);return!0},function(a,b,c){b=R(b,c);null!=b&&("string"===typeof b&&Xa(b),null!=b&&(J(a,c,0),"number"===typeof b?(a=a.h,Sa(b),xb(a,H,I)):(c=Xa(b),xb(a.h,c.i,c.h))))}),Zc=X(function(a,b,c){if(0!==a.i)return!1;S(b,c,rb(a.h));return!0},Vc),$c=X(function(a,b,c){if(0!==a.i)return!1;a=rb(a.h);cc(b,c,a,0);return!0},Vc),ad=X(function(a,b,c){if(0!==a.i)return!1;a=tb(a.h);cc(b,c,a,!1);return!0},function(a,b,c){b=R(b,c);b=null==b?b:!!b;null!=b&&(J(a,c,0),a.h.h.push(b?1:
0))}),bd=X(function(a,b,c){if(2!==a.i)return!1;var d=rb(a.h)>>>0;a=a.h;var e=ub(a,d);a=a.i;if(fb){var f=a,g;(g=eb)||(g=eb=new TextDecoder("utf-8",{fatal:!0}));a=e+d;f=0===e&&a===f.length?f:f.subarray(e,a);try{var h=g.decode(f)}catch(r){if(void 0===db){try{g.decode(new Uint8Array([128]))}catch(p){}try{g.decode(new Uint8Array([97])),db=!0}catch(p){db=!1}}!db&&(eb=void 0);throw r;}}else{h=e;d=h+d;e=[];for(var k=null,l,m;h<d;)l=a[h++],128>l?e.push(l):224>l?h>=d?bb():(m=a[h++],194>l||128!==(m&192)?(h--,
bb()):e.push((l&31)<<6|m&63)):240>l?h>=d-1?bb():(m=a[h++],128!==(m&192)||224===l&&160>m||237===l&&160<=m||128!==((f=a[h++])&192)?(h--,bb()):e.push((l&15)<<12|(m&63)<<6|f&63)):244>=l?h>=d-2?bb():(m=a[h++],128!==(m&192)||0!==(l<<28)+(m-144)>>30||128!==((f=a[h++])&192)||128!==((g=a[h++])&192)?(h--,bb()):(l=(l&7)<<18|(m&63)<<12|(f&63)<<6|g&63,l-=65536,e.push((l>>10&1023)+55296,(l&1023)+56320))):bb(),8192<=e.length&&(k=cb(k,e),e.length=0);h=cb(k,e)}S(b,c,h);return!0},function(a,b,c){b=R(b,c);if(null!=
b){var d=!1;d=void 0===d?!1:d;if(hb){if(d&&/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(b))throw Error("Found an unpaired surrogate");b=(gb||(gb=new TextEncoder)).encode(b)}else{for(var e=0,f=new Uint8Array(3*b.length),g=0;g<b.length;g++){var h=b.charCodeAt(g);if(128>h)f[e++]=h;else{if(2048>h)f[e++]=h>>6|192;else{if(55296<=h&&57343>=h){if(56319>=h&&g<b.length){var k=b.charCodeAt(++g);if(56320<=k&&57343>=k){h=1024*(h-55296)+k-56320+65536;f[e++]=h>>18|240;f[e++]=h>>
12&63|128;f[e++]=h>>6&63|128;f[e++]=h&63|128;continue}else g--}if(d)throw Error("Found an unpaired surrogate");h=65533}f[e++]=h>>12|224;f[e++]=h>>6&63|128}f[e++]=h&63|128}}b=e===f.length?f:f.subarray(0,e)}J(a,c,2);yb(a.h,b.length);Hb(a,a.h.end());Hb(a,b)}}),cd=X(function(a,b,c,d,e){if(2!==a.i)return!1;Ub(b);var f=R(b,c);d=ec(Yb(f,d,!0));f!==d&&T(b,c,d);Eb(a,d,e);return!0},function(a,b,c,d,e){b=dc(b,d,c);null!=b&&(c=Ib(a,c),e(b,a),Jb(a,c))}),dd=X(function(a,b,c,d,e){if(2!==a.i)return!1;Eb(a,hc(b,c,
d),e);return!0},function(a,b,c,d,e){b=gc(b,d,c);if(null!=b)for(d=0;d<b.length;d++){var f=Ib(a,c);e(b[d],a);Jb(a,f)}}),ed=X(function(a,b,c){if(0!==a.i)return!1;S(b,c,rb(a.h));return!0},function(a,b,c){b=R(b,c);null!=b&&(b=parseInt(b,10),J(a,c,0),zb(a.h,b))});function fd(a){return function(b,c){a:{if(Fb.length){var d=Fb.pop();d.setOptions(c);pb(d.h,b,c);b=d}else b=new Bb(b,c);try{var e=Bc(a);var f=Cc(new e.P,b,e);break a}finally{e=b.h,e.i=null,e.s=!1,e.l=0,e.j=0,e.h=0,e.S=!1,b.l=-1,b.i=-1,100>Fb.length&&Fb.push(b)}f=void 0}return f}}function gd(a){return function(){var b=new Gb;Lc(this,b,Kc(a));Hb(b,b.h.end());for(var c=new Uint8Array(b.i),d=b.j,e=d.length,f=0,g=0;g<e;g++){var h=d[g];c.set(h,f);f+=h.length}b.j=[c];return c}};function hd(a){W.call(this,a)}B(hd,W);var id=[hd,1,Zc,2,Y,3,bd,4,bd];hd.prototype.l=gd(id);function jd(a){W.call(this,a,-1,kd)}B(jd,W);jd.prototype.addClassification=function(a,b){hc(this,1,hd,a,b);return this};var kd=[1],ld=fd([jd,1,dd,id]);function md(a){W.call(this,a)}B(md,W);var nd=[md,1,Y,2,Y,3,Y,4,Y,5,Y];md.prototype.l=gd(nd);function od(a){W.call(this,a,-1,pd)}B(od,W);var pd=[1],qd=fd([od,1,dd,nd]);function rd(a){W.call(this,a)}B(rd,W);var sd=[rd,1,Y,2,Y,3,Y,4,Y,5,Y,6,Yc],td=fd(sd);rd.prototype.l=gd(sd);function ud(a){W.call(this,a)}B(ud,W);var vd=[ud,1,Y,2,Y,3,Y];function wd(a){W.call(this,a,-1,xd)}B(wd,W);var xd=[3,7,8,9],yd=[wd,1,ed,2,ed,3,Z,4,cd,vd,5,Zc,6,Zc,7,Z,8,Z,9,Z];function zd(a){W.call(this,a)}B(zd,W);var Ad=[zd,1,Xc,2,Xc,3,Xc];function Bd(a){W.call(this,a)}B(Bd,W);var Cd=[Bd,1,Xc,2,Xc,3,Xc];function Dd(a){W.call(this,a)}B(Dd,W);var Ed=[Dd,1,$c,2,cd,Cd,3,cd,Ad,4,ad];function Fd(a){W.call(this,a,-1,Gd)}B(Fd,W);var Gd=[2,4,5,6],Hd=[Fd,1,$c,2,dd,Ed,3,Xc,4,Z,5,Z,6,Z];function Id(a){W.call(this,a,-1,Jd)}B(Id,W);var Jd=[2,5,6],Kd=fd([Id,1,$c,2,dd,Hd,3,cd,yd,4,Wc,5,Z,6,Z]);function Ld(a,b,c){c=a.createShader(0===c?a.VERTEX_SHADER:a.FRAGMENT_SHADER);a.shaderSource(c,b);a.compileShader(c);if(!a.getShaderParameter(c,a.COMPILE_STATUS))throw Error("Could not compile WebGL shader.\n\n"+a.getShaderInfoLog(c));return c};function Md(a){return gc(a,hd,1).map(function(b){return{index:ic(b),qa:V(b,2),label:null!=R(b,3)?jc(R(b,3),""):void 0,displayName:null!=R(b,4)?jc(R(b,4),""):void 0}})};function Nd(a){return{x:V(a,1),y:V(a,2),z:V(a,3),visibility:null!=ac(a,4)?V(a,4):void 0}};function Od(a,b){this.i=a;this.h=b;this.m=0}
function Pd(a,b,c){Qd(a,b);if("function"===typeof a.h.canvas.transferToImageBitmap)return Promise.resolve(a.h.canvas.transferToImageBitmap());if(c)return Promise.resolve(a.h.canvas);if("function"===typeof createImageBitmap)return createImageBitmap(a.h.canvas);void 0===a.j&&(a.j=document.createElement("canvas"));return new Promise(function(d){a.j.height=a.h.canvas.height;a.j.width=a.h.canvas.width;a.j.getContext("2d",{}).drawImage(a.h.canvas,0,0,a.h.canvas.width,a.h.canvas.height);d(a.j)})}
function Qd(a,b){var c=a.h;if(void 0===a.s){var d=Ld(c,"\n  attribute vec2 aVertex;\n  attribute vec2 aTex;\n  varying vec2 vTex;\n  void main(void) {\n    gl_Position = vec4(aVertex, 0.0, 1.0);\n    vTex = aTex;\n  }",0),e=Ld(c,"\n  precision mediump float;\n  varying vec2 vTex;\n  uniform sampler2D sampler0;\n  void main(){\n    gl_FragColor = texture2D(sampler0, vTex);\n  }",1),f=c.createProgram();c.attachShader(f,d);c.attachShader(f,e);c.linkProgram(f);if(!c.getProgramParameter(f,c.LINK_STATUS))throw Error("Could not compile WebGL program.\n\n"+
c.getProgramInfoLog(f));d=a.s=f;c.useProgram(d);e=c.getUniformLocation(d,"sampler0");a.l={O:c.getAttribLocation(d,"aVertex"),N:c.getAttribLocation(d,"aTex"),ya:e};a.v=c.createBuffer();c.bindBuffer(c.ARRAY_BUFFER,a.v);c.enableVertexAttribArray(a.l.O);c.vertexAttribPointer(a.l.O,2,c.FLOAT,!1,0,0);c.bufferData(c.ARRAY_BUFFER,new Float32Array([-1,-1,-1,1,1,1,1,-1]),c.STATIC_DRAW);c.bindBuffer(c.ARRAY_BUFFER,null);a.u=c.createBuffer();c.bindBuffer(c.ARRAY_BUFFER,a.u);c.enableVertexAttribArray(a.l.N);c.vertexAttribPointer(a.l.N,
2,c.FLOAT,!1,0,0);c.bufferData(c.ARRAY_BUFFER,new Float32Array([0,1,0,0,1,0,1,1]),c.STATIC_DRAW);c.bindBuffer(c.ARRAY_BUFFER,null);c.uniform1i(e,0)}d=a.l;c.useProgram(a.s);c.canvas.width=b.width;c.canvas.height=b.height;c.viewport(0,0,b.width,b.height);c.activeTexture(c.TEXTURE0);a.i.bindTexture2d(b.glName);c.enableVertexAttribArray(d.O);c.bindBuffer(c.ARRAY_BUFFER,a.v);c.vertexAttribPointer(d.O,2,c.FLOAT,!1,0,0);c.enableVertexAttribArray(d.N);c.bindBuffer(c.ARRAY_BUFFER,a.u);c.vertexAttribPointer(d.N,
2,c.FLOAT,!1,0,0);c.bindFramebuffer(c.DRAW_FRAMEBUFFER?c.DRAW_FRAMEBUFFER:c.FRAMEBUFFER,null);c.clearColor(0,0,0,0);c.clear(c.COLOR_BUFFER_BIT);c.colorMask(!0,!0,!0,!0);c.drawArrays(c.TRIANGLE_FAN,0,4);c.disableVertexAttribArray(d.O);c.disableVertexAttribArray(d.N);c.bindBuffer(c.ARRAY_BUFFER,null);a.i.bindTexture2d(0)}function Rd(a){this.h=a};var Sd=new Uint8Array([0,97,115,109,1,0,0,0,1,4,1,96,0,0,3,2,1,0,10,9,1,7,0,65,0,253,15,26,11]);function Td(a,b){return b+a}function Ud(a,b){window[a]=b}function Vd(a){var b=document.createElement("script");b.setAttribute("src",a);b.setAttribute("crossorigin","anonymous");return new Promise(function(c){b.addEventListener("load",function(){c()},!1);b.addEventListener("error",function(){c()},!1);document.body.appendChild(b)})}
function Wd(){return D(function(a){switch(a.h){case 1:return a.s=2,C(a,WebAssembly.instantiate(Sd),4);case 4:a.h=3;a.s=0;break;case 2:return a.s=0,a.l=null,a.return(!1);case 3:return a.return(!0)}})}
function Xd(a){this.h=a;this.listeners={};this.l={};this.L={};this.s={};this.v={};this.M=this.u=this.ha=!0;this.I=Promise.resolve();this.ga="";this.D={};this.locateFile=a&&a.locateFile||Td;if("object"===typeof window)var b=window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/";else if("undefined"!==typeof location)b=location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/";else throw Error("solutions can only be loaded on a web page or in a web worker");
this.ia=b;if(a.options){b=A(Object.keys(a.options));for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=a.options[c].default;void 0!==d&&(this.l[c]="function"===typeof d?d():d)}}}v=Xd.prototype;v.close=function(){this.j&&this.j.delete();return Promise.resolve()};
function Yd(a){var b,c,d,e,f,g,h,k,l,m,r;return D(function(p){switch(p.h){case 1:if(!a.ha)return p.return();b=void 0===a.h.files?[]:"function"===typeof a.h.files?a.h.files(a.l):a.h.files;return C(p,Wd(),2);case 2:c=p.i;if("object"===typeof window)return Ud("createMediapipeSolutionsWasm",{locateFile:a.locateFile}),Ud("createMediapipeSolutionsPackedAssets",{locateFile:a.locateFile}),g=b.filter(function(n){return void 0!==n.data}),h=b.filter(function(n){return void 0===n.data}),k=Promise.all(g.map(function(n){var q=
Zd(a,n.url);if(void 0!==n.path){var t=n.path;q=q.then(function(y){a.overrideFile(t,y);return Promise.resolve(y)})}return q})),l=Promise.all(h.map(function(n){return void 0===n.simd||n.simd&&c||!n.simd&&!c?Vd(a.locateFile(n.url,a.ia)):Promise.resolve()})).then(function(){var n,q,t;return D(function(y){if(1==y.h)return n=window.createMediapipeSolutionsWasm,q=window.createMediapipeSolutionsPackedAssets,t=a,C(y,n(q),2);t.i=y.i;y.h=0})}),m=function(){return D(function(n){a.h.graph&&a.h.graph.url?n=C(n,
Zd(a,a.h.graph.url),0):(n.h=0,n=void 0);return n})}(),C(p,Promise.all([l,k,m]),7);if("function"!==typeof importScripts)throw Error("solutions can only be loaded on a web page or in a web worker");d=b.filter(function(n){return void 0===n.simd||n.simd&&c||!n.simd&&!c}).map(function(n){return a.locateFile(n.url,a.ia)});importScripts.apply(null,fa(d));e=a;return C(p,createMediapipeSolutionsWasm(Module),6);case 6:e.i=p.i;a.m=new OffscreenCanvas(1,1);a.i.canvas=a.m;f=a.i.GL.createContext(a.m,{antialias:!1,
alpha:!1,va:"undefined"!==typeof WebGL2RenderingContext?2:1});a.i.GL.makeContextCurrent(f);p.h=4;break;case 7:a.m=document.createElement("canvas");r=a.m.getContext("webgl2",{});if(!r&&(r=a.m.getContext("webgl",{}),!r))return alert("Failed to create WebGL canvas context when passing video frame."),p.return();a.K=r;a.i.canvas=a.m;a.i.createContext(a.m,!0,!0,{});case 4:a.j=new a.i.SolutionWasm,a.ha=!1,p.h=0}})}
function $d(a){var b,c,d,e,f,g,h,k;return D(function(l){if(1==l.h){if(a.h.graph&&a.h.graph.url&&a.ga===a.h.graph.url)return l.return();a.u=!0;if(!a.h.graph||!a.h.graph.url){l.h=2;return}a.ga=a.h.graph.url;return C(l,Zd(a,a.h.graph.url),3)}2!=l.h&&(b=l.i,a.j.loadGraph(b));c=A(Object.keys(a.D));for(d=c.next();!d.done;d=c.next())e=d.value,a.j.overrideFile(e,a.D[e]);a.D={};if(a.h.listeners)for(f=A(a.h.listeners),g=f.next();!g.done;g=f.next())h=g.value,ae(a,h);k=a.l;a.l={};a.setOptions(k);l.h=0})}
v.reset=function(){var a=this;return D(function(b){a.j&&(a.j.reset(),a.s={},a.v={});b.h=0})};
v.setOptions=function(a,b){var c=this;if(b=b||this.h.options){for(var d=[],e=[],f={},g=A(Object.keys(a)),h=g.next();!h.done;f={X:f.X,Y:f.Y},h=g.next())if(h=h.value,!(h in this.l&&this.l[h]===a[h])){this.l[h]=a[h];var k=b[h];void 0!==k&&(k.onChange&&(f.X=k.onChange,f.Y=a[h],d.push(function(l){return function(){var m;return D(function(r){if(1==r.h)return C(r,l.X(l.Y),2);m=r.i;!0===m&&(c.u=!0);r.h=0})}}(f))),k.graphOptionXref&&(h=Object.assign({},{calculatorName:"",calculatorIndex:0},k.graphOptionXref,
{valueNumber:1===k.type?a[h]:0,valueBoolean:0===k.type?a[h]:!1,valueString:2===k.type?a[h]:""}),e.push(h)))}if(0!==d.length||0!==e.length)this.u=!0,this.H=(void 0===this.H?[]:this.H).concat(e),this.F=(void 0===this.F?[]:this.F).concat(d)}};
function be(a){var b,c,d,e,f,g,h;return D(function(k){switch(k.h){case 1:if(!a.u)return k.return();if(!a.F){k.h=2;break}b=A(a.F);c=b.next();case 3:if(c.done){k.h=5;break}d=c.value;return C(k,d(),4);case 4:c=b.next();k.h=3;break;case 5:a.F=void 0;case 2:if(a.H){e=new a.i.GraphOptionChangeRequestList;f=A(a.H);for(g=f.next();!g.done;g=f.next())h=g.value,e.push_back(h);a.j.changeOptions(e);e.delete();a.H=void 0}a.u=!1;k.h=0}})}
v.initialize=function(){var a=this;return D(function(b){return 1==b.h?C(b,Yd(a),2):3!=b.h?C(b,$d(a),3):C(b,be(a),0)})};function Zd(a,b){var c,d;return D(function(e){if(b in a.L)return e.return(a.L[b]);c=a.locateFile(b,"");d=fetch(c).then(function(f){return f.arrayBuffer()});a.L[b]=d;return e.return(d)})}v.overrideFile=function(a,b){this.j?this.j.overrideFile(a,b):this.D[a]=b};v.clearOverriddenFiles=function(){this.D={};this.j&&this.j.clearOverriddenFiles()};
v.send=function(a,b){var c=this,d,e,f,g,h,k,l,m,r;return D(function(p){switch(p.h){case 1:if(!c.h.inputs)return p.return();d=1E3*(void 0===b||null===b?performance.now():b);return C(p,c.I,2);case 2:return C(p,c.initialize(),3);case 3:e=new c.i.PacketDataList;f=A(Object.keys(a));for(g=f.next();!g.done;g=f.next())if(h=g.value,k=c.h.inputs[h]){a:{var n=a[h];switch(k.type){case "video":var q=c.s[k.stream];q||(q=new Od(c.i,c.K),c.s[k.stream]=q);0===q.m&&(q.m=q.i.createTexture());if("undefined"!==typeof HTMLVideoElement&&
n instanceof HTMLVideoElement){var t=n.videoWidth;var y=n.videoHeight}else"undefined"!==typeof HTMLImageElement&&n instanceof HTMLImageElement?(t=n.naturalWidth,y=n.naturalHeight):(t=n.width,y=n.height);y={glName:q.m,width:t,height:y};t=q.h;t.canvas.width=y.width;t.canvas.height=y.height;t.activeTexture(t.TEXTURE0);q.i.bindTexture2d(q.m);t.texImage2D(t.TEXTURE_2D,0,t.RGBA,t.RGBA,t.UNSIGNED_BYTE,n);q.i.bindTexture2d(0);q=y;break a;case "detections":q=c.s[k.stream];q||(q=new Rd(c.i),c.s[k.stream]=q);
q.data||(q.data=new q.h.DetectionListData);q.data.reset(n.length);for(y=0;y<n.length;++y){t=n[y];var x=q.data,F=x.setBoundingBox,P=y;var L=t.la;var u=new rd;U(u,1,L.sa);U(u,2,L.ta);U(u,3,L.height);U(u,4,L.width);U(u,5,L.rotation);S(u,6,L.pa);L=u.l();F.call(x,P,L);if(t.ea)for(x=0;x<t.ea.length;++x){u=t.ea[x];F=q.data;P=F.addNormalizedLandmark;L=y;u=Object.assign({},u,{visibility:u.visibility?u.visibility:0});var G=new md;U(G,1,u.x);U(G,2,u.y);U(G,3,u.z);u.visibility&&U(G,4,u.visibility);u=G.l();P.call(F,
L,u)}if(t.ba)for(x=0;x<t.ba.length;++x)F=q.data,P=F.addClassification,L=y,u=t.ba[x],G=new hd,U(G,2,u.qa),u.index&&S(G,1,u.index),u.label&&S(G,3,u.label),u.displayName&&S(G,4,u.displayName),u=G.l(),P.call(F,L,u)}q=q.data;break a;default:q={}}}l=q;m=k.stream;switch(k.type){case "video":e.pushTexture2d(Object.assign({},l,{stream:m,timestamp:d}));break;case "detections":r=l;r.stream=m;r.timestamp=d;e.pushDetectionList(r);break;default:throw Error("Unknown input config type: '"+k.type+"'");}}c.j.send(e);
return C(p,c.I,4);case 4:e.delete(),p.h=0}})};
function ce(a,b,c){var d,e,f,g,h,k,l,m,r,p,n,q,t,y;return D(function(x){switch(x.h){case 1:if(!c)return x.return(b);d={};e=0;f=A(Object.keys(c));for(g=f.next();!g.done;g=f.next())h=g.value,k=c[h],"string"!==typeof k&&"texture"===k.type&&void 0!==b[k.stream]&&++e;1<e&&(a.M=!1);l=A(Object.keys(c));g=l.next();case 2:if(g.done){x.h=4;break}m=g.value;r=c[m];if("string"===typeof r)return t=d,y=m,C(x,de(a,m,b[r]),14);p=b[r.stream];if("detection_list"===r.type){if(p){var F=p.getRectList();for(var P=p.getLandmarksList(),
L=p.getClassificationsList(),u=[],G=0;G<F.size();++G){var ba=td(F.get(G)),ge=V(ba,1),he=V(ba,2),ie=V(ba,3),je=V(ba,4),ke=V(ba,5,0),Qa=void 0;Qa=void 0===Qa?0:Qa;ba={la:{sa:ge,ta:he,height:ie,width:je,rotation:ke,pa:jc(R(ba,6),Qa)},ea:gc(qd(P.get(G)),md,1).map(Nd),ba:Md(ld(L.get(G)))};u.push(ba)}F=u}else F=[];d[m]=F;x.h=7;break}if("proto_list"===r.type){if(p){F=Array(p.size());for(P=0;P<p.size();P++)F[P]=p.get(P);p.delete()}else F=[];d[m]=F;x.h=7;break}if(void 0===p){x.h=3;break}if("float_list"===
r.type){d[m]=p;x.h=7;break}if("proto"===r.type){d[m]=p;x.h=7;break}if("texture"!==r.type)throw Error("Unknown output config type: '"+r.type+"'");n=a.v[m];n||(n=new Od(a.i,a.K),a.v[m]=n);return C(x,Pd(n,p,a.M),13);case 13:q=x.i,d[m]=q;case 7:r.transform&&d[m]&&(d[m]=r.transform(d[m]));x.h=3;break;case 14:t[y]=x.i;case 3:g=l.next();x.h=2;break;case 4:return x.return(d)}})}
function de(a,b,c){var d;return D(function(e){return"number"===typeof c||c instanceof Uint8Array||c instanceof a.i.Uint8BlobList?e.return(c):c instanceof a.i.Texture2dDataOut?(d=a.v[b],d||(d=new Od(a.i,a.K),a.v[b]=d),e.return(Pd(d,c,a.M))):e.return(void 0)})}
function ae(a,b){for(var c=b.name||"$",d=[].concat(fa(b.wants)),e=new a.i.StringList,f=A(b.wants),g=f.next();!g.done;g=f.next())e.push_back(g.value);f=a.i.PacketListener.implement({onResults:function(h){for(var k={},l=0;l<b.wants.length;++l)k[d[l]]=h.get(l);var m=a.listeners[c];m&&(a.I=ce(a,k,b.outs).then(function(r){r=m(r);for(var p=0;p<b.wants.length;++p){var n=k[d[p]];"object"===typeof n&&n.hasOwnProperty&&n.hasOwnProperty("delete")&&n.delete()}r&&(a.I=r)}))}});a.j.attachMultiListener(e,f);e.delete()}
v.onResults=function(a,b){this.listeners[b||"$"]=a};za("Solution",Xd);za("OptionType",{BOOL:0,NUMBER:1,ua:2,0:"BOOL",1:"NUMBER",2:"STRING"});function ee(a){var b=ic(a);var c=dc(a,zd,3);c={x:V(c,1),y:V(c,2),depth:V(c,3)};a=dc(a,Bd,2);a={x:V(a,1),y:V(a,2),z:V(a,3)};return{id:b,point2d:c,point3d:a}}function fe(a){var b=Kd(a);a=[];b=gc(b,Fd,2);for(var c=0;c<b.length;c++)a.push({id:ic(b[c]),keypoints:gc(b[c],Dd,2).map(ee),visibility:V(b[c],3),scale:bc(b[c],6),translation:bc(b[c],5),rotation:bc(b[c],4)});return a};function le(a){switch(a){case "Camera":return"object_detection_3d_camera.tflite";case "Chair":return"object_detection_3d_chair.tflite";case "Cup":return"object_detection_3d_cup.tflite";default:return"object_detection_3d_sneakers.tflite"}}function me(a){switch(a){case "Camera":return"Camera";case "Chair":return"Chair";case "Cup":return"Coffee cup, Mug";default:return"Footwear"}}
var ne={focalX:{type:1,graphOptionXref:{calculatorType:"Lift2DFrameAnnotationTo3DCalculator",fieldName:"normalized_focal_x"}},focalY:{type:1,graphOptionXref:{calculatorType:"Lift2DFrameAnnotationTo3DCalculator",fieldName:"normalized_focal_y"}},principalX:{type:1,graphOptionXref:{calculatorType:"Lift2DFrameAnnotationTo3DCalculator",fieldName:"normalized_principal_point_x"}},principalY:{type:1,graphOptionXref:{calculatorType:"Lift2DFrameAnnotationTo3DCalculator",fieldName:"normalized_principal_point_y"}},
allowedLabels:{type:2,graphOptionXref:{calculatorName:"ConstantSidePacketCalculatorAllowedLabels",calculatorType:"ConstantSidePacketCalculator",fieldName:"string_value"}}};
function oe(a){var b=this;a=a||{};this.h=new Xd({locateFile:a.locateFile,files:[{url:"objectron_solution_packed_assets_loader.js"},{simd:!1,url:"objectron_solution_wasm_bin.js"},{simd:!0,url:"objectron_solution_simd_wasm_bin.js"}],graph:{url:"objectron.binarypb"},inputs:{image:{type:"video",stream:"input_frames_gpu"}},listeners:[{wants:["lifted_objects","image_transformed"],outs:{image:"image_transformed",objectDetections:{type:"proto",stream:"lifted_objects",transform:fe}}}],options:{useCpuInference:{type:0,
graphOptionXref:{calculatorType:"InferenceCalculator",fieldName:"use_cpu_inference"},default:"object"!==typeof window||void 0===window.navigator?!1:"iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";").includes(navigator.platform)||navigator.userAgent.includes("Mac")&&"ontouchend"in document},selfieMode:{type:0,default:!1,graphOptionXref:{calculatorType:"GlScalerCalculator",calculatorIndex:1,fieldName:"flip_horizontal"}},maxNumObjects:{type:1,default:5,graphOptionXref:{calculatorType:"ConstantSidePacketCalculator",
calculatorName:"ConstantSidePacketCalculatorMaxNumObjects",fieldName:"int_value"}},staticImageMode:{type:0,default:!0,graphOptionXref:{calculatorType:"ConstantSidePacketCalculator",calculatorName:"objectrongpusubgraph__ConstantSidePacketCalculator",fieldName:"bool_value"}},minDetectionConfidence:{type:1,default:.5,graphOptionXref:{calculatorType:"TensorsToDetectionsCalculator",calculatorName:"objectrongpusubgraph__objectdetectionoidv4subgraph__TensorsToDetectionsCalculator",fieldName:"min_score_thresh"}},
minTrackingConfidence:{type:1,default:.99,graphOptionXref:{calculatorType:"ThresholdingCalculator",calculatorName:"objectrongpusubgraph__boxlandmarksubgraph__ThresholdingCalculator",fieldName:"threshold"}},modelName:{default:"Shoe",onChange:function(c){var d,e,f,g;return D(function(h){if(1==h.h)return d=c,b.h.setOptions({allowedLabels:me(d)},ne),e=le(d),f="object_detection_3d.tflite",C(h,Zd(b.h,e),2);g=h.i;b.h.overrideFile(f,g);return h.return(!0)})}},focalLength:{default:[1,1],onChange:function(c){var d;
return D(function(e){d=c;b.i=d;b.h.setOptions({focalX:d[0],focalY:d[1]},ne);return e.return(!0)})}},principalPoint:{default:[0,0],onChange:function(c){var d;return D(function(e){d=c;b.j=d;b.h.setOptions({principalX:d[0],principalY:d[1]},ne);return e.return(!0)})}},imageSize:{onChange:function(c){var d,e,f,g;return D(function(h){if(void 0===b.i||void 0===b.j)return console.error('"focalLength" and "principalPoint" must be set if setting image size'),h.return();d=c;e=[d[0]/2,d[1]/2];f=[b.i[0]/e[0],
b.i[1]/e[1]];g=[b.j[0]/e[0],b.j[1]/e[1]];b.setOptions({focalLength:f,principalPoint:g});h.h=0})}}}})}v=oe.prototype;v.close=function(){this.h.close();return Promise.resolve()};v.onResults=function(a){this.h.onResults(a)};v.initialize=function(){var a=this;return D(function(b){return C(b,a.h.initialize(),0)})};v.reset=function(){this.h.reset()};v.send=function(a){var b=this;return D(function(c){return C(c,b.h.send(a),0)})};v.setOptions=function(a){this.h.setOptions(a)};za("Objectron",oe);
za("BOX_CONNECTIONS",[[1,2],[2,4],[4,3],[3,1],[5,6],[6,8],[8,7],[7,5],[1,5],[2,6],[3,7],[4,8]]);za("BOX_KEYPOINTS",{CENTER:0,BACK_BOTTOM_LEFT:1,FRONT_BOTTOM_LEFT:2,BACK_TOP_LEFT:3,FRONT_TOP_LEFT:4,BACK_BOTTOM_RIGHT:5,FRONT_BOTTOM_RIGHT:6,BACK_TOP_RIGHT:7,FRONT_TOP_RIGHT:8});za("VERSION","0.4.1675468480");}).call(this);
